site_name: Nest Documentation
theme:
  name: material
  highlightjs: true
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      use_pygments: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
nav:
  - Introduction: index.md
  - General syntax: syntax.md
  - Built-in libraries:
    - Coroutine Library: coroutine_library.md
    - Error library: error_library.md
    - Filesystem library: filesystem_library.md
    - Input-output library: io_library.md
    - Iterator utilities library: iterator_utilities_library.md
    - JSON library: json_library.md
    - Math library: math_library.md
    - Random library: random_library.md
    - Sequence utilities library: sequence_utilities_library.md
    - String utilities library: string_utilities_library.md
    - System library: system_library.md
    - Time and date library: time_library.md
    - UTF-8 library: utf8_library.md
  - C ABI: c_abi.md
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - js/highlight.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/atom-one-light.min.css
  - https://fonts.googleapis.com/css?family=Fira Code
  - css/font.css