site_name: Nest Documentation
theme:
  name: material
  highlightjs: true
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      use_pygments: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      permalink: "#"
nav:
  - Introduction: index.md
  - Installation: installation.md
  - General syntax: syntax.md
  - Tutorials:
    - tutorials/c-lib-tutorial.md
    - tutorials/using-generate_docs.md
  - Standard Library:
    - stdlib/codecs_library.md
    - stdlib/coroutine_library.md
    - stdlib/time_library.md
    - stdlib/error_library.md
    - stdlib/filesystem_library.md
    - stdlib/io_library.md
    - stdlib/iterator_utilities_library.md
    - stdlib/json_library.md
    - stdlib/math_library.md
    - stdlib/random_library.md
    - stdlib/sequence_utilities_library.md
    - stdlib/string_utilities_library.md
    - stdlib/system_library.md
  - C API:
    - c_api/c_api_index.md
    - c_api/c_api_reference.md
    - argv_parser.h: c_api/c_api-argv_parser.md
    - compiler.h: c_api/c_api-compiler.md
    - encoding.h: c_api/c_api-encoding.md
    - error.h: c_api/c_api-error.md
    - file.h: c_api/c_api-file.md
    - format.h: c_api/c_api-format.md
    - function.h: c_api/c_api-function.md
    - ggc.h: c_api/c_api-ggc.md
    - global_consts.h: c_api/c_api-global_consts.md
    - hash.h: c_api/c_api-hash.md
    - instructions.h: c_api/c_api-instructions.md
    - interpreter.h: c_api/c_api-interpreter.md
    - iter.h: c_api/c_api-iter.md
    - lexer.h: c_api/c_api-lexer.md
    - lib_import.h: c_api/c_api-lib_import.md
    - llist.h: c_api/c_api-llist.md
    - map.h: c_api/c_api-map.md
    - mem.h: c_api/c_api-mem.md
    - nest.h: c_api/c_api-nest.md
    - nodes.h: c_api/c_api-nodes.md
    - obj.h: c_api/c_api-obj.md
    - obj_ops.h: c_api/c_api-obj_ops.md
    - optimizer.h: c_api/c_api-optimizer.md
    - parser.h: c_api/c_api-parser.md
    - runtime_stack.h: c_api/c_api-runtime_stack.md
    - sequence.h: c_api/c_api-sequence.md
    - simple_types.h: c_api/c_api-simple_types.md
    - str.h: c_api/c_api-str.md
    - tokens.h: c_api/c_api-tokens.md
    - type.h: c_api/c_api-type.md
    - typedefs.h: c_api/c_api-typedefs.md
    - var_table.h: c_api/c_api-var_table.md
  - Version History: changes.md
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js
  - js/highlight.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/atom-one-dark.min.css
  - https://fonts.googleapis.com/css?family=Fira Code
  - css/styles.css
