name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: sudo bash ./configure.sh x64
    - name: Compile
      working-directory: ./build/linux/makefiles
      run: make all
    - name: Install Nest
      run: |
        mkdir -p ./build/linux/linux_libs
        cp -r ./libs/_nest_files/* ./build/linux/linux_libs
        for i in ./build/linux/linux_libs/*.nest; do
          python3 ./build/update_nest_file.py "${i}"
        done
        sudo mkdir -p /usr/lib/nest/
        sudo cp -r ./build/linux/linux_libs/* /usr/lib/nest
        sudo cp ./build/linux/linux_release/x64/*.cnest /usr/lib/nest
        sudo cp ./build/linux/linux_release/x64/nest /usr/bin
        sudo cp ./build/linux/linux_release/x64/libnest.so /usr/lib
        sudo ldconfig
    - name: Run Tests
      working-directory: ./tests
      run: |
        nest run_tests.nest
        cat test_output.txt
