name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [ "main", "pre-stable" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Compile and Install
      working-directory: ./build/linux
      run: make install
    - name: Run Tests
      working-directory: ./build/linux
      run: |
        make test-release
        cat ../../tests/test_output.txt
