name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: sudo bash ./configure.sh x64
    - name: Compile x64
      working-directory: ./build/linux/makefiles
      run: make all
    #- name: Compile x86
    #  working-directory: ./build/linux/makefiles
    #  run: make all-x86
    - name: Install Nest
      run: |
        mkdir -p ./build/linux/linux_libs
        cp ./libs/_nest_files/* ./build/linux/linux_libs
        for i in ./build/linux/linux_libs/*; do
          python3 ./build/update_nest_file.py "${i}"
        done
        sudo mkdir -p "/usr/lib/nest"
        sudo cp ./build/linux/linux_libs/std* /usr/lib/nest
        sudo cp ./build/linux/linux_release/x64/std* /usr/lib/nest
        sudo cp ./build/linux/linux_release/x64/nest /usr/bin
        sudo cp ./build/linux/linux_release/x64/libnest.so /usr/lib
    - name: Run Tests
      working-directory: ./tests
      run: |
        nest run_tests.nest
        cat test_output.txt
